[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'tpope/vim-commentary'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'kchmck/vim-coffee-script'

[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'fatih/vim-go'

[[plugins]]
repo = 'w0rp/ale'

[[plugins]]
repo = 'HerringtonDarkholme/yats.vim'

